### ISSUE TITLE
Having issue when running "put-object" to s3 bucket through ozone

### ISSUE THREAD

**Issue by lixmgl** [apple/batch-processing-gateway#1]
I am getting "An error occurred (500) when calling the PutObject operation (reached max retries: 2): Internal Server Error" when running "sh ./init-s3-bucket.sh".
Found this error from ozone pod log: 

2022-10-25 23:11:44 ERROR ObjectEndpoint:208 - Exception occurred in PutObject
SCM_IN_SAFE_MODE org.apache.hadoop.ozone.om.exceptions.OMException: SafeModePrecheck failed for allocateBlock
	at org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB.handleError(OzoneManagerProtocolClientSideTranslatorPB.java:613)
	at org.apache.hadoop.ozone.om.protocolPB.OzoneManagerProtocolClientSideTranslatorPB.openKey(OzoneManagerProtocolClientSideTranslatorPB.java:604)
	at org.apache.hadoop.ozone.client.rpc.RpcClient.createKey(RpcClient.java:801)
	at org.apache.hadoop.ozone.client.rpc.RpcClient.createKey(RpcClient.java:758)
	at org.apache.hadoop.ozone.client.OzoneBucket.createKey(OzoneBucket.java:511)
	at org.apache.hadoop.ozone.s3.endpoint.ObjectEndpoint.put(ObjectEndpoint.java:195)
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1459)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
	at org.apache.hadoop.ozone.s3.RootPageDisplayFilter.doFilter(RootPageDisplayFilter.java:53)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.apache.hadoop.ozone.s3.EmptyContentTypeFilter.doFilter(EmptyContentTypeFilter.java:76)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.apache.hadoop.hdds.server.http.HttpServer2$QuotingInputFilter.doFilter(HttpServer2.java:1678)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.apache.hadoop.hdds.server.http.NoCacheFilter.doFilter(NoCacheFilter.java:48)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:602)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by tongtianqi777** [comment]
Assuming this error was from M1 (Apple Silicon). As stated in the getting started guide:
```
Up to today [Ozone does not support arm64 (Apple Silicon) well](https://issues.apache.org/jira/browse/HDDS-6263). If you are using Apple Silicon and want to set up dev services locally, you can choose to use an Intel machine, or use a remote K8s cluster / S3 endpoint as an alternative.
```

The current official Ozone image was made for Intel chips, and we've seen issues when running it on M1.
The alternatives are:
- Use AWS S3 (and even EKS) if you already have it available. this way you can run bigger Spark jobs for dev works too.
- Rebuild the Ozone image for M1, and use the custom image in the Ozone helm chart
- Use Intel machines (less optimal choice as you'd need to stick with it)

**Comment by lixmgl** [comment]
Actually the error is from aws eks cluster. Ozone was deployed to the cluster.

**Comment by leletan** [comment]
```SCM_IN_SAFE_MODE org.apache.hadoop.ozone.om.exceptions.OMException: SafeModePrecheck failed for allocateBlock```
This seems pointing to `SCM_IN_SAFE_MODE` check failure - and it could be due to [this](https://github.com/apple/batch-processing-gateway/blob/43a500816a17dfb611b8951f955a3a75a652ba8b/dev-setup/ozone/config-configmap.yaml#L29) config that requiring 3 datanodes.
Can you double check if all 3 datanodes pods are running healthily in `local-ozone` namespace? You should be able to see sth like this:

```
$ kubectl -n local-ozone get pods
NAME         READY   STATUS    RESTARTS   AGE
datanode-0   1/1     Running   0          29s
datanode-1   1/1     Running   0          24s
datanode-2   1/1     Running   0          20s
om-0         1/1     Running   0          29s
s3g-0        1/1     Running   0          29s
scm-0        1/1     Running   0          29s

**Comment by tongtianqi777** [comment]
The Ozone chart in this repo is to help quickly set up an environment fully locally, so that no EKS / AWS S3 are needed. If you are already using AWS EKS to deploy Ozone, is it possible to use AWS S3 to get around this problem?

**Comment by lixmgl** [comment]
yes, i am able to see 3 datanodes: 

rainieli-D9VN436:scripts rainieli$ kubectl -n local-ozone get pods
NAME         READY   STATUS    RESTARTS   AGE
datanode-0   1/1     Running   0          21h
datanode-1   1/1     Running   0          21h
datanode-2   1/1     Running   0          21h
om-0         1/1     Running   0          21h
s3g-0        1/1     Running   0          21h
scm-0        1/1     Running   0          21h

After future debugging, we saw this error:
Unable to find enough nodes that meet the space requirement of 1073741824 bytes for metadata and 5368709120 bytes for data in healthy node set. Nodes required: 1 Found: 0

The issue is caused by 5G storage setting  in datanode: (https://github.com/apple/batch-processing-gateway/blob/main/dev-setup/ozone/datanode-statefulset.yaml#L68). 

By increasing 5G to 10G, we are able to put-object to new s3 bucket through ozone.

**Comment by tongtianqi777** [comment]
@lixmgl got it thanks for looking into it. do you want to bring up a PR and resolve this issue in the repo?

**Comment by lixmgl** [comment]
@tongtianqi777 sure, I will create a PR to resolve this issue.

**Comment by lixmgl** [comment]
PR: https://github.com/apple/batch-processing-gateway/pull/4 
please review.
